<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Polson.Drawing.Svg</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="5.2.1" />
    <PackageReference Include="Svg.Custom" Version="5.2.1" />
    <PackageReference Include="Svg.Model" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polson.Runtime\Polson.Runtime.csproj" />
  </ItemGroup>

</Project>
