"""Creates a Polson project and the ADK app that serves it, in one act.

Run it::

    python-adk\\Scripts\\python.exe src\\adk_agent\\newproject.py demo --workflow logo \\
        --prompt "a mark for a bookbindery"

Or call `create(...)` from the web layer, which is where this is headed.

**Why an app per project rather than an app per workflow.** ADK scopes everything by app name —
`/apps/{app_name}/users/{user_id}/sessions/{session_id}` — and one app means one `McpToolset`, built
once and cached, so one studio server and one project directory for every session that app serves.
An app per *workflow* would therefore make everyone drawing a logo share one set of `artifacts/`.
An app per *project* gives each brief its own studio, which is what a visitor expects and what the
run record needs to stay legible.

**It is dynamic because ADK's app listing is not cached.** `AgentLoader.list_agents` does a fresh
`os.listdir` on every call; only `load_agent` caches, and it caches per name. So a directory written
here appears in `/list-apps` on the next request with no restart. Verified against a running server.

The generated `agent.py` bakes **absolute paths**, exactly as `ProjectGenerator.McpConfig` does and
for the same reason it gives: a relative path resolves against whatever working directory the host
chose, and when it resolves wrongly the server still starts and still draws — it just records
nothing. Regenerate after moving the repository.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

#: Repository root, from `src/adk_agent/newproject.py`.
REPO_ROOT = Path(__file__).resolve().parents[2]

#: Where `studio.py` lives, and so what a generated app must put on `sys.path`.
RUNTIME_DIR = Path(__file__).resolve().parent

#: The agents directory `main.py` serves. Generated wholesale, and gitignored wholesale — nothing
#: committed lives here, which is why the factory sits one level up instead.
APPS_DIR = RUNTIME_DIR / "apps"

#: Where generated projects go by default. Their own directory, not inside the runtime.
PROJECTS_DIR = REPO_ROOT / "projects"

CLI_DLL = REPO_ROOT / "bin" / "cli" / "Polson.CLI.dll"

#: ADK app names become URL segments and Python module names. `create-project` already constrains
#: its id to letters, digits, dot, underscore and dash; a dot is legal there and not here.
VALID_APP_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9_\-]*$")

_AGENT_PY = '''\
"""Generated by newproject.py for the project `{project_id}`. Do not edit.

Regenerate rather than editing: this file is derived from the project directory, and an edit here is
one the next generation silently discards. Absolute paths are baked in deliberately — see
newproject.py — so regenerate after moving the repository.
"""

import sys

# `studio.py` sits one level above the agents directory, so that a shared factory is not itself
# listed as a broken app. ADK only puts the agents directory on the path, hence this line.
sys.path.insert(0, r"{runtime_dir}")

from studio import build

root_agent = build(r"{project_dir}")
'''


class GenerateError(RuntimeError):
    """Something went wrong, with a message saying what to do about it."""


def _run_create_project(
    projects_dir: Path, project_id: str, workflow: str,
    prompt: str | None, type_: str | None, force: bool,
) -> Path:
    """Shells out to the one thing that knows how to build a project."""
    if not CLI_DLL.is_file():
        raise GenerateError(f"no CLI at {CLI_DLL}. Build it with dotnet build on src/Polson.CLI.")
    if shutil.which("dotnet") is None:
        raise GenerateError("`dotnet` is not on PATH; the MCP server cannot be launched either.")

    projects_dir.mkdir(parents=True, exist_ok=True)
    # Positional: <parent-directory> <project-id> [sdk]. `agy` selects GEMINI.md, which is what
    # studio.py reads — ADK is Gemini, so the agy spelling is the right one here.
    args = [
        "dotnet", str(CLI_DLL), "create-project",
        str(projects_dir), project_id, "agy", "--workflow", workflow,
    ]
    if prompt:
        args += ["--prompt", prompt]
    if type_:
        args += ["--type", type_]
    if force:
        args += ["--force"]

    done = subprocess.run(args, capture_output=True, text=True)
    if done.returncode != 0:
        detail = (done.stderr or done.stdout or "").strip()
        raise GenerateError(f"create-project failed ({done.returncode}).\n{detail}")

    project = projects_dir / project_id
    if not project.is_dir():
        raise GenerateError(f"create-project reported success but {project} does not exist.")
    return project


def write_app(project_dir: Path, app_name: str, apps_dir: Path = APPS_DIR) -> Path:
    """Writes the ADK app package that serves `project_dir`. Idempotent."""
    if not VALID_APP_NAME.match(app_name):
        raise GenerateError(
            f"{app_name!r} is not usable as an app name. It becomes a URL segment and a Python "
            "module name, so it must start with a letter and hold only letters, digits, "
            "underscores and dashes."
        )

    package = apps_dir / app_name
    package.mkdir(parents=True, exist_ok=True)
    (package / "__init__.py").write_text("from . import agent\n", encoding="utf-8")
    (package / "agent.py").write_text(
        _AGENT_PY.format(
            project_id=app_name,
            runtime_dir=str(RUNTIME_DIR),
            project_dir=str(project_dir.resolve()),
        ),
        encoding="utf-8",
    )
    return package


def create(
    project_id: str, *, workflow: str = "logo", prompt: str | None = None,
    type_: str | None = None, force: bool = False,
    projects_dir: Path = PROJECTS_DIR, apps_dir: Path = APPS_DIR,
) -> tuple[Path, Path]:
    """Generates the project and its app. Returns `(project_dir, app_package)`."""
    if not VALID_APP_NAME.match(project_id):
        raise GenerateError(
            f"{project_id!r} cannot be an app name — it must start with a letter and hold only "
            "letters, digits, underscores and dashes."
        )
    project = _run_create_project(projects_dir, project_id, workflow, prompt, type_, force)
    return project, write_app(project, project_id, apps_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("project_id", help="Project id, and the ADK app name it is served under.")
    parser.add_argument("--workflow", default="logo",
                        help="logo, infographic, drawing, comic, painting, comic_studio, harness.")
    parser.add_argument("--prompt", help="The subject, in a line. Treated as untrusted data.")
    parser.add_argument("--type", dest="type_", help="Narrows the workflow's direction.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing project.")
    parser.add_argument("--projects-dir", type=Path, default=PROJECTS_DIR)
    args = parser.parse_args(argv)

    try:
        project, package = create(
            args.project_id, workflow=args.workflow, prompt=args.prompt,
            type_=args.type_, force=args.force, projects_dir=args.projects_dir)
    except GenerateError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    print(f"project  {project}")
    print(f"app      {package}")
    print(f"serving  /apps/{args.project_id}/...   (appears in /list-apps without a restart)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
