@echo off
REM Generated by `polson create-project`. Invoked by .agents/hooks.json.
REM A hook runs with its working directory set to this folder, not the project root,
REM which is why every path below is absolute.
"C:\Projects\Polson\bin\cli\Polson.CLI.exe" preserve-chatlog --host agy --project-dir "C:\Projects\Polson\tests\agent\infographic\agy\inf-2"
