<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>$(ProjectAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(ProjectAssemblyVersion)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polson.Runtime\Polson.Runtime.csproj" />
    <ProjectReference Include="..\Polson.Drawing.Svg\Polson.Drawing.Svg.csproj" />
  </ItemGroup>

</Project>
